### ISSUE TITLE
Problem while running the astrology software

### ISSUE THREAD

**Issue by raveeshs** [erajasekar/erajasekar.github.io#1]
Hello Rajasekar, Thank you very much for sharing the astrology software but I have absolutely no clue about coding but then I learned to install run and compile. Can you please help me to identify the error below?  How can I make it work. 

 [javac] D:\Vedic Horo Reads\Astrosoft-master\Astrosoft-master\src\app\astrosoft\util\Internalization.java:110: error: unmappable character (0x81) for encoding windows-1252

    [javac]             unsupportedMsgs.put(AstrosoftTableColumn.OjaYugmarasyamsaBala.name(), "┬╡┬â├ö├¼├?├â┬ä┬í├╡┬║");

    [javac]                                                                                             ^

    [javac] D:\Vedic Horo Reads\Astrosoft-master\Astrosoft-master\src\app\astrosoft\util\Internalization.java:120: error: unmappable character (0x81) for encoding windows-1252

    [javac]             unsupportedMsgs.put(Thithi.Ashtami.name(), "┬½┬ë┬╝├?┬ó");

    [javac]                                                                ^

    [javac] D:\Vedic Horo Reads\Astrosoft-master\Astrosoft-master\src\app\astrosoft\util\Internalization.java:126: error: unmappable character (0x81) for encoding windows-1252

    [javac]             unsupportedMsgs.put("Ayushman", "┬¼├ö┬ë├?┬í├╜");

    [javac]                                                     ^

    [javac] 59 errors

    [javac] 1 warning

 

BUILD FAILED

D:\Vedic Horo Reads\Astrosoft-master\Astrosoft-master\build.xml:46: Compile failed; see the compiler error output for details.

 

Total time: 39 seconds

**Comment by erajasekar** [comment]
You can resolve it by placing the "utf8" encoding in javac in the build.xml file.
