### ISSUE TITLE
GitPitch Down - Unable to Find/See Presentations

### ISSUE THREAD

**Issue by MissChervinsky** [erajasekar/erajasekar.github.io#2]
https://erajasekar.medium.com/what-middle-school-students-need-to-know-about-computer-science-and-software-engineering-job-14e12404fe73

GitPitch has been taken down / out of service so I'm unable to find or get to your presentations for this.

I'm a middle school teacher currently and would love to do an entire large unit about algorithms just like this! I simply cannot see your presentation due to the GitPitch problem and have found no other way to really reach out to you other than this.

Thank you!
Ms. Chervinsky

**Comment by erajasekar** [comment]
Hi @MissChervinsky , I converted all slides into PDF and here is link to download them.

https://www.dropbox.com/sh/6zftwwspgry5nrk/AACo64SgMjSUsq5OqjzQY-vva?dl=0

Hope this helps.
